---
bases:
  - ../../../../bases/infrastructure/copybot/core
  - ../../../../bases/infrastructure/copybot/hermes
  - ../../../../bases/infrastructure/copybot/harmonia

namespace: default

configMapGenerator:
  - name: copybot
    envs:
      - env.ini

replicas:
  - name: copybot-hermes
    count: 1
  - name: copybot-harmonia
    count: 1

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: copybot
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: copybot
                env:
                  - name: POSTGRES_HOST
                    valueFrom:
                      secretKeyRef:
                        name: azure-pgfs
                        key: common_placeholder
