---
bases:
  - ../base

nameSuffix: -cron-scheduler

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: polaris
        labels:
          component: cron-scheduler
      spec:
        selector:
          matchLabels:
            component: cron-scheduler
        template:
          metadata:
            labels:
              component: cron-scheduler
            annotations:
              prometheus.io/port: '9100'
              prometheus.io/scrape: 'true'
              prometheus.io/job: polaris
          spec:
            containers:
              - name: app
                command: ["linkerd-await", "--"]
                args: ["python", "-m", "polaris.core.cli", "cron-scheduler"]
                resources:
                  limits:
                    memory: 1Gi
                  requests:
                    memory: 1Gi
