---
bases:
  - ../base

nameSuffix: -cron-scheduler

commonLabels:
  component: cron-scheduler

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/priorityClassName
        value: bink-medium-tasks
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["python", "-m", "polaris.core.cli", "cron-scheduler"]
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 1Gi
