bases:
  - github.com/kubernetes/ingress-nginx/deploy/static/provider/baremetal?ref=controller-v1.1.0

patches:
  - path: patch-nodeport.yaml
  - path: patch-annotations.yaml
  - path: patch-logging.yaml
  - path: patch-metrics.yaml
  - path: patch-antiaffinity.yaml
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/replicas
        value: 2
