bases:
  - "../../../../../bases/olympus/atalanta/transactors/costa"
  - "../../../../../bases/olympus/atalanta/distributors/costa"

namespace: perf-txm-e2e

configMapGenerator:
  - name: atalanta-costa
    files:
      - ../configs/costa.toml

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: atalanta-costa
      spec:
        template:
          spec:
            volumes:
              - name: config
                configMap:
                  defaultMode: 400
                  name: atalanta-costa
                  