---
resources:
  - ../../../../bases/olympus/europa/api
  - ../../../../bases/olympus/europa/migrator
  - aad.yaml


namespace: olympus

configMapGenerator:
  - name: europa
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: europa
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: europa
                env:
                  - name: EUROPA_DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-postgres
                        key: url_europa
                  - name: KEY_VAULT_URI
                    valueFrom:
                      secretKeyRef:
                        key: url
                        name: azure-keyvault
                  - name: KEYVAULT_URI
                    valueFrom:
                      secretKeyRef:
                        key: url
                        name: azure-keyvault
