---
bases:
  - ../../../../bases/olympus/atlas/api
  - ../../../../bases/olympus/atlas/consumer
  - ../../../../bases/olympus/atlas/migrator

configMapGenerator:
  - name: atlas
    namespace: default
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: atlas
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: atlas
                env:
                  - name: ATLAS_DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-postgres
                        key: url_atlas
