---
resources:
  - ../base

nameSuffix: -cron-scheduler

commonLabels:
  component: cron-scheduler

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/metadata/annotations
        value: {"prometheus.io/port":"9100","prometheus.io/scrape":"true","prometheus.io/job":"carina"}
      - op: add
        path: /spec/template/spec/priorityClassName
        value: bink-medium-tasks
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["python", "-m", "carina.core.cli", "cron-scheduler"]
