apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../bases/devops/backups/essentials/
- ./atlas
- ./carina
- ./eos
- ./europa
- ./hades
- ./harmonia
- ./hermes
- ./polaris
- ./pontus
- ./vela
namespace: backups
