---
bases:
  - ../../../../bases/portal/bullsquid

namespace: portal

configMapGenerator:
  - name: bullsquid
    files:
      - config/config.toml

patches:
  - target:
      kind: ServiceProfile
    patch: |-
      - op: replace
        path: /metadata/name
        value: bullsquid.portal.svc.cluster.local
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: bullsquid
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: bullsquid
                env:
                  - name: DATABASE_DSN
                    valueFrom:
                      secretKeyRef:
                        name: azure-pgfs
                        key: common_placeholder
                volumeMounts:
                  - name: config
                    mountPath: /app/config.toml
                    subPath: config.toml
                  - name: database-dsn
                    mountPath: /var/run/secrets/bullsquid
                    readOnly: true
            volumes:
              - name: config
                configMap:
                  defaultMode: 400
                  name: bullsquid
              - name: database-dsn
                secret:
                  secretName: azure-pgfs
                  items:
                    - key: common_placeholder
                      path: database_dsn
