bases:
- ../../../../bases/olympus/midas/api
- ../../../../bases/olympus/midas/beat
- ../../../../bases/olympus/midas/celery
- ../../../../bases/olympus/midas/consumer

resources:
- aad.yaml

patches:
- path: env.yaml
  target:
    kind: Deployment
