---
bases:
  - ../base

nameSuffix: -worker

commonLabels:
  app: pyxis
  component: worker

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: pyxis
      spec:
        template:
          spec:
            containers:
              - name: app
                command:
                  - locust
                  - --worker
                  - --master-host=pyxis-controller
                  - --master-port=5557
                  - --locustfile=locust_performance_testing/locustfile.py
              - name: nginx
                command:
                  - nginx
                image: binkcore.azurecr.io/pyxis:latest
                resources:
                  limits:
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 128Mi
