---
resources:
  - ../../../../bases/olympus/zephyrus
  - azureidentity.yaml

namespace: default

configMapGenerator:
  - name: zephyrus
    envs:
      - env.ini

replicas:
  - name: zephyrus-api
    count: 3

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: zephyrus
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: zephyrus
