---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-horizon
  namespace: default
  labels:
    app: event-horizon
spec:
  selector:
    matchLabels:
      app: event-horizon
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: app
      labels:
        app: event-horizon
        aadpodidbinding: event-horizon
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - event-horizon
                topologyKey: topology.kubernetes.io/zone
              weight: 100
      serviceAccountName: event-horizon
      priorityClassName: event-horizon
      containers:
        - name: app
          image: binkcore.azurecr.io/event-horizon:latest
          imagePullPolicy: Always
          command: ["linkerd-await", "--"]
          args:
            - gunicorn
            - --error-logfile=-
            - --access-logfile=-
            - --bind=0.0.0.0:9000
            - wsgi:app
          resources:
            limits:
              cpu: 1000m
              memory: 1664Mi
            requests:
              cpu: 10m
              memory: 1664Mi
          securityContext:
            runAsGroup: 65534
            runAsUser: 65534
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
      imagePullSecrets:
        - name: binkcore.azurecr.io
