---
bases:
  - ../../default/metis

namespace: trusted-channels

replicas:
  - name: metis
    count: 0

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: metis
      spec:
        template:
          spec:
            containers:
              - name: app
                env:
                  - name: PONTUS_DATABASE_URI
                    value: postgresql://postgres@postgres:5432/pontus
