---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: lloyds-sit-ingress
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./overlays/uksouth-sandbox/lloyds-sit/ingress
  prune: true
  dependsOn:
    - name: cert-manager
    - name: keyvault2kube
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: flux-cluster-vars
