apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-kiroshi
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./overlays/uksouth-staging/devops/kiroshi
  dependsOn:
    - name: linkerd-control-plane
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  images:
    - name: binkcore.azurecr.io/kiroshi
      newTag: staging-v1.2.0 # {"$imagepolicy": "flux-system:kiroshi:tag"}
  postBuild:
    substituteFrom:
      - kind: Secret
        name: azure-identities
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: kiroshi
  namespace: flux-system
spec:
  image: binkcore.azurecr.io/kiroshi
  interval: 10m0s
  secretRef:
    name: binkcore.azurecr.io
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: kiroshi
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kiroshi
  filterTags:
    pattern: staging-v(?P<ts>\d+(\.\d+)*)$
    extract: $ts
  policy:
    semver:
      range: '>0.0.1'
