---
bases:
  - github.com/terrycain/keyvault2kube/deploy?ref=2.3.1

configMapGenerator:
  - name: keyvault2kube
    namespace: kube-system
    files:
      - config/pgbouncer.yaml

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: KEY_VAULT_URLS
            value: https://bink-uksouth-prod-inf.vault.azure.net/
          - name: ALL_NAMESPACES
            value: "True"
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          mountPath: /app/templates
          name: template-config
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: template-config
          configMap:
            defaultMode: 420
            name: keyvault2kube
  - target:
      kind: AzureIdentity
    patch: |-
      - op: replace
        path: /spec/resourceID
        value: /subscriptions/79560fde-5831-481d-8c3c-e812ef5046e5/resourcegroups/uksouth-prod/providers/Microsoft.ManagedIdentity/userAssignedIdentities/bink-uksouth-prod-infra-sync
  - target:
      kind: AzureIdentity
    patch: |-
      - op: replace
        path: /spec/clientID
        value: 36ec85ad-ba0f-4c6a-926b-d6f9145af890
