---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: 'true'
  name: tableau-admin.${cluster_name}.${cluster_location}.bink.sh-healthz
  namespace: tableau
spec:
  rules:
    - host: tableau-admin.${cluster_name}.${cluster_location}.bink.sh
      http:
        paths:
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: healthz
                port:
                  number: 80
  tls:
    - hosts:
        - tableau-admin.${cluster_name}.${cluster_location}.bink.sh
