---
bases:
  - ../base

nameSuffix: -tx-history-consumer

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: polaris
        labels:
          component: tx-history-consumer
      spec:
        selector:
          matchLabels:
            component: tx-history-consumer
        template:
          metadata:
            labels:
              component: tx-history-consumer
          spec:
            containers:
              - name: app
                command: ["linkerd-await", "--"]
                args: ["python", "-m", "polaris.core.cli", "tx-history-consumer"]
