---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harmonia-reporter
  namespace: monitoring
  labels:
    app: harmonia-reporter
spec:
  selector:
    matchLabels:
      app: harmonia-reporter
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: app
        linkerd.io/inject: enabled
      labels:
        app: harmonia-reporter
    spec:
      containers:
        - name: app
          image: binkcore.azurecr.io/harmonia_archive_reporter:prod-2021-08-27T132214Z
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 128Mi
          ports:
            - containerPort: 9000
        - name: alerts
          image: binkcore.azurecr.io/harmonia_archive_reporter:prod-2021-08-27T132214Z
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 128Mi
          args:
            - python3
            - alerts.py
      imagePullSecrets:
        - name: binkcore.azurecr.io
