---
resources:
  - ../../../bases/datawarehouse/airbyte
  - ../../../bases/datawarehouse/prefect
  - ../../../bases/datawarehouse/tableau

patches:
  - target:
      kind: Endpoints
    patch: |
      - op: replace
        path: /subsets/0/addresses/0/ip
        value: 10.11.131.4

  - target:
      kind: Deployment
      name: prefect-server
    patch: |
      - op: replace
        path: /spec/template/spec/initContainers/0/args
        value: ["-c", "prefect config set PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://$(DATABASE_USER):$(DATABASE_PASS)@$(DATABASE_HOST):5432/prefect && prefect config set PREFECT_API_URL=https://prefect.gb.bink.com/api"]
  
  - target:
      kind: Deployment
      name: prefect-agent
    patch: |
      - op: replace
        path: /spec/template/spec/initContainers/0/args
        value: ["-c", "prefect config set PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://$(DATABASE_USER):$(DATABASE_PASS)@$(DATABASE_HOST):5432/prefect && prefect config set PREFECT_API_URL=http://prefect-server:4200/api"]

  - target:
      kind: Job
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["/bin/bash", "-c", "cd /app/data-warehouse/Prefect && make deploy-prod && cd /app/data-warehouse-dashboards/Prefect && make deploy-prod"]
