---
bases:
  - ../../../../bases/olympus/hermes/core
  - ../../../../bases/olympus/hermes/api
  - ../../../../bases/olympus/hermes/beat
  - ../../../../bases/olympus/hermes/celery
  - ../../../../bases/olympus/hermes/migrator

resources:
  - aad.yaml

namespace: barclays-oat

configMapGenerator:
  - name: hermes
    envs:
      - env.ini

patches:
  - target:
      kind: ServiceProfile
    patch: |-
      - op: replace
        path: /metadata/name
        value: hermes-api.barclays-oat.svc.cluster.local
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hermes
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: hermes
                env:
                  - name: HERMES_BLOB_STORAGE_DSN
                    valueFrom:
                      secretKeyRef:
                        key: connection_string
                        name: azure-storage-barclays-oat
                  - name: HERMES_DATABASE_URL_BARE
                    valueFrom:
                      secretKeyRef:
                        name: azure-pgfs
                        key: common_barclays_oat_hermes
                  - name: HERMES_DATABASE_URL
                    value: $(HERMES_DATABASE_URL_BARE)&application_name=hermes
