---
resources:
  - ../../../../bases/olympus/boreas/api
  - aad.yaml

configMapGenerator:
  - name: boreas
    namespace: default
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: boreas
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: boreas
                env:
                  - name: KEYVAULT_URI
                    valueFrom:
                      secretKeyRef:
                        key: url
                        name: azure-keyvault
                  - name: KEY_VAULT
                    valueFrom:
                      secretKeyRef:
                        key: url
                        name: azure-keyvault
