bases:
- github.com/kubernetes/ingress-nginx/deploy/static/provider/baremetal?ref=controller-v0.44.0

patches:
- path: patch-nodeport.yaml
- path: patch-annotations.yaml
- path: patch-logging.yaml
- path: patch-metrics.yaml
- path: patch-antiaffinity.yaml
