bases:
- ../../../bases/qa/pyqa/bink
- ../../../bases/qa/pyqa/barclays

resources:
- azureidentity.yaml

patches:
- path: env-barclays.yaml
  target:
    name: pyqa-barclays
    kind: Deployment
- path: env-bink.yaml
  target:
    name: pyqa-bink
    kind: Deployment
