---
resources:
  - aad.yaml

bases:
  - ../../../../bases/olympus/midas/api
  - ../../../../bases/olympus/midas/beat
  - ../../../../bases/olympus/midas/celery
  - ../../../../bases/olympus/midas/consumer

configMapGenerator:
  - name: midas
    namespace: default
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: midas
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: midas
