---
bases:
  - ../../default/hermes

namespace: trusted-channels

replicas:
  - name: hermes
    count: 0

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hermes
      spec:
        template:
          spec:
            containers:
              - name: app
                env:
                  - name: HERMES_BLOB_STORAGE_DSN
                    valueFrom:
                      secretKeyRef:
                        key: connection_string
                        name: azure-storage-common
                  - name: HERMES_DATABASE_URL
                    value: postgresql://postgres@postgres:5432/hermes
