---
bases:
  - ../../../../bases/cosmos/polaris/core
  - ../../../../bases/cosmos/polaris/api
  - ../../../../bases/cosmos/polaris/migrator
  - ../../../../bases/cosmos/polaris/task-worker
  - ../../../../bases/cosmos/polaris/cron-scheduler
  - ../../../../bases/cosmos/polaris/tx-history-consumer

namespace: bpl-testing

resources:
  - aad.yaml

configMapGenerator:
  - name: polaris
    envs:
      - env.ini
  - name: polaris-scripts
    files:
      - migrator.py

patches:
  - target:
      kind: Deployment
      name: polaris-task-worker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["python", "-m", "polaris.core.cli", "task-worker"]
  - target:
      kind: Deployment
      name: polaris-cron-scheduler
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["python", "-m", "polaris.core.cli", "cron-scheduler"]
  - target:
      kind: Deployment
      name: polaris-tx-history-consumer
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["python", "-m", "polaris.core.cli", "tx-history-consumer"]
  - target:
      kind: Deployment
      name: polaris-migrator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: polaris
      spec:
        template:
          spec:
            containers:
              - name: app
                args: ["python", "/app/migrator.py"]
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: polaris
      spec:
        template:
          spec:
            containers:
              - name: app
                env:
                  - name: BLOB_STORAGE_DSN
                    valueFrom:
                      secretKeyRef:
                        key: connection_string
                        name: azure-storage-common
                envFrom:
                  - configMapRef:
                      name: polaris
                volumeMounts:
                - name: polaris-scripts
                  mountPath: /app/migrator.py
                  subPath: migrator.py
            volumes:
              - name: polaris-scripts
                configMap:
                  name: polaris-scripts
                  items:
                    - key: migrator.py
                      path: migrator.py
