---
bases:
  - ../../../../bases/cosmos/polaris/core
  - ../../../../bases/cosmos/polaris/api
  - ../../../../bases/cosmos/polaris/migrator
  - ../../../../bases/cosmos/polaris/task-worker
  - ../../../../bases/cosmos/polaris/cron-scheduler
  - ../../../../bases/cosmos/polaris/tx-history-consumer

namespace: bpl-testing

resources:
  - aad.yaml

configMapGenerator:
  - name: polaris
    envs:
      - env.ini
  - name: polaris-scripts
    files:
      - migrator.py

patches:
  - target:
      kind: Deployment
      name: polaris-migrator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: polaris
      spec:
        template:
          spec:
            containers:
              - name: app
                args: ["python", "/app/migrator.py"]
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: polaris
      spec:
        template:
          spec:
            containers:
              - name: app
                env:
                  - name: BLOB_STORAGE_DSN
                    valueFrom:
                      secretKeyRef:
                        key: connection_string_primary
                        name: azure-storage
                  - name: KEY_VAULT_URI
                    valueFrom:
                      secretKeyRef:
                        key: url
                        name: azure-keyvault
                envFrom:
                  - configMapRef:
                      name: polaris
                volumeMounts:
                - name: polaris-scripts
                  mountPath: /app/migrator.py
                  subPath: migrator.py
            volumes:
              - name: polaris-scripts
                configMap:
                  name: polaris-scripts
                  items:
                    - key: migrator.py
                      path: migrator.py
