---
bases:
  - ../base

nameSuffix: -task-worker

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: vela
        labels:
          component: task-worker
      spec:
        selector:
          matchLabels:
            component: task-worker
        template:
          metadata:
            annotations:
              prometheus.io/port: '9100'
              prometheus.io/scrape: 'true'
              prometheus.io/job: task-worker
            labels:
              component: task-worker
          spec:
            containers:
              - name: app
                command: ["linkerd-await", "--"]
                args: ["python", "-m", "vela.core.cli", "task-worker"]
