---
bases:
  - ../../../../bases/olympus/angelia

resources:
  - aad.yaml

namespace: default

configMapGenerator:
  - name: angelia
    envs:
      - env.ini

replicas:
  - name: angelia-api
    count: 6

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: angelia
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: angelia
                env:
                  - name: POSTGRES_DSN
                    valueFrom:
                      secretKeyRef:
                        name: azure-pgfs
                        key: common_hermes
