---
bases:
  - barclays
  - bink

resources:
  - azureidentity.yaml

namespace: default

configMapGenerator:
  - name: pyqa-bink
    envs:
      - config/bink.ini
  - name: pyqa-barclays
    envs:
      - config/barclays.ini

patches:
  - target:
      kind: CronJob
    patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env
        value:
          - name: BLOB_STORAGE_DSN
            valueFrom:
              secretKeyRef:
                key: blob_connection_string_primary
                name: azure-storage
          - name: NFS_STORAGE_DSN
            valueFrom:
              secretKeyRef:
                key: nfs_connection_string_primary
                name: azure-storage
          - name: VAULT_URL
            valueFrom:
              secretKeyRef:
                key: url
                name: azure-keyvault
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/1/env
        value:
          - name: BLOB_STORAGE_DSN
            valueFrom:
              secretKeyRef:
                key: connection_string_primary
                name: azure-storage
          - name: NFS_STORAGE_DSN
            valueFrom:
              secretKeyRef:
                key: nfs_connection_string_primary
                name: azure-storage
          - name: HERMES_DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: azure-postgres
                key: url_hermes
          - name: HARMONIA_DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: azure-postgres
                key: url_harmonia
          - name: SNOWSTORM_DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: azure-postgres
                key: url_snowstorm
          - name: VAULT_URL
            valueFrom:
              secretKeyRef:
                key: url
                name: azure-keyvault
  - target:
      kind: CronJob
      name: pyqa-bink
    patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: pyqa-bink
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/1/envFrom
        value:
          - configMapRef:
              name: pyqa-bink
  - target:
      kind: CronJob
      name: pyqa-barclays
    patch: |-
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/envFrom
        value:
          - configMapRef:
              name: pyqa-barclays
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/1/envFrom
        value:
          - configMapRef:
              name: pyqa-barclays
