---
bases:
  - ../base

nameSuffix: -celery

commonLabels:
  component: celery

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/priorityClassName
        value: bink-high-tasks
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["celery", "-A", "hermes", "worker", "--without-gossip", "--without-mingle", "--loglevel=info", "--pool=prefork", "--concurrency=2", "--queues=ubiquity-async-midas,record-history", "--events"]
