apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../bases/cronjob

nameSuffix: -freshservice

commonLabels:
  component: freshservice

patches:
  - target:
      kind: CronJob
    patch: |
      - op: replace
        path: /spec/schedule
        value: "0 1 * * *"
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/args
        value: ["stormctl", "job", "freshservice", "--days=1"]
