resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- daemonset.yaml
- serviceaccount.yaml
- namespace.yaml

secretGenerator:
  - name: elasticsearch-auth
    namespace: monitoring
    literals:
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=H~E=*1u1pdSmeoA

patches:
  - target:
      kind: DaemonSet
    patch: |-
      - op: add
        path: /metadata/annotations/buoyant.cloud~1excluded
        value: "true"
