---
resources:
  - ../base

nameSuffix: -task-worker

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["python", "-m", "hubble.cli", "task-worker"]
      - op: add
        path: /spec/template/spec/priorityClassName
        value: bink-medium-tasks
