---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: bpl-ingress
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./overlays/uksouth-prod/bpl/ingress
  prune: true
  dependsOn:
    - name: cert-manager
    - name: ingress-nginx
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
