---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobsf
  labels:
    app: mobsf
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mobsf
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: app
        linkerd.io/inject: enabled
      labels:
        app: mobsf
    spec:
      initContainers:
        - name: chown
          command: [chown, -R, 9901:9901, /mobsf]
          image: docker.io/alpine:3
          volumeMounts:
            - name: mobsf
              mountPath: /mobsf/
      containers:
        - name: app
          image: docker.io/opensecurity/mobile-security-framework-mobsf:v3.6.0
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 512Mi
          volumeMounts:
            - name: mobsf
              mountPath: /home/mobsf/.MobSF
      priorityClassName: bink-high-tasks
      volumes:
        - name: mobsf
          persistentVolumeClaim:
            claimName: mobsf
