---
resources:
  - ../../../../bases/olympus/midas/api
  - ../../../../bases/olympus/midas/beat
  - ../../../../bases/olympus/midas/celery
  - ../../../../bases/olympus/midas/consumer
  - ../../../../bases/olympus/midas/migrator
  - ../../../../bases/olympus/midas/worker
  - aad.yaml

replicas:
  - name: midas
    count: 3
  - name: midas-beat
    count: 3
  - name: midas-migrator
    count: 1

namespace: default

configMapGenerator:
  - name: midas
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: midas
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: midas
                env:
                  - name: POSTGRES_DSN
                    valueFrom:
                      secretKeyRef:
                        name: azure-postgres
                        key: url_placeholder
                  - name: REDIS_URL
                    valueFrom:
                      secretKeyRef:
                        key: url_primary
                        name: azure-redis
