---
bases:
  - ../../../../bases/cosmos/vela/core
  - ../../../../bases/cosmos/vela/api
  - ../../../../bases/cosmos/vela/migrator
  - ../../../../bases/cosmos/vela/task-worker
  - ../../../../bases/cosmos/vela/cron-scheduler

namespace: bpl

resources:
  - aad.yaml

configMapGenerator:
  - name: vela
    namespace: default
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
      name: vela-task-worker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["python", "-m", "vela.core.cli", "task-worker"]
  - target:
      kind: Deployment
      name: vela-cron-scheduler
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["python", "-m", "vela.core.cli", "cron-scheduler"]
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: vela
      spec:
        template:
          spec:
            containers:
              - name: app
                env:
                  - name: SQLALCHEMY_DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-pgfs
                        key: common_vela
                envFrom:
                  - configMapRef:
                      name: vela
