apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bridge
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./overlays/uksouth-prod/devops/bridge
  dependsOn:
    - name: linkerd-control-plane
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  images:
    - name: binkcore.azurecr.io/bridge
      newTag: 2022-08-26T163254Z # {"$imagepolicy": "flux-system:bridge:tag"}
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: bridge
  namespace: flux-system
spec:
  image: binkcore.azurecr.io/bridge
  interval: 10m0s
  secretRef:
    name: binkcore.azurecr.io
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: bridge
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bridge
  filterTags:
    pattern: ^(?P<ts>\d{4}-\d{2}-\d{2}T\d{6}Z)$
    extract: $ts
  policy:
    alphabetical:
      order: asc
