apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-tools
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./overlays/uksouth-tools/ingress-tools
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  