bases:
  - "../../core/deployment"

commonLabels:
  component: distributor-visa-settlement

nameSuffix: -distributor-visa-settlement

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: [ cargo, run, --bin, distributor ]
