---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pypi
  name: pypi
  namespace: default
  annotations:
    buoyant.cloud/excluded: 'true'
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pypi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: pypi
      labels:
        app: pypi
    spec:
      containers:
        - image: binkcore.azurecr.io/pypi:latest
          command: ["uwsgi", "/etc/pypicloud/config.ini"]
          name: pypi
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /etc/pypicloud/
              readOnly: true
          resources:
            requests:
              cpu: 100m
              memory: 4096Mi
            limits:
              cpu: 4000m
              memory: 4096Mi
      imagePullSecrets:
        - name: binkcore.azurecr.io
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: config
          secret:
            secretName: pypi-config
