---
resources:
  - ../base

nameSuffix: -task-worker

commonLabels:
  component: task-worker

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/priorityClassName
        value: bink-medium-tasks
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["cosmos", "task-worker"]
      - op: remove
        path: /spec/template/spec/containers/0/readinessProbe
      - op: remove
        path: /spec/template/spec/containers/0/livenessProbe
