---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: 'true'
  name: prefect.${cluster_name}.${cluster_location}.bink.sh
  namespace: datawarehouse
spec:
  rules:
    - host: prefect.${cluster_name}.${cluster_location}.bink.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prefect
                port:
                  number: 4200
  tls:
    - hosts:
        - prefect.${cluster_name}.${cluster_location}.bink.sh
