---
resources:
  - ../../../../bases/olympus/iris

replicas:
  - name: iris
    count: 0

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: iris
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: iris
                env:
                  - name: STORAGE_ACCOUNT_CONNECTION_STRING
                    valueFrom:
                      secretKeyRef:
                        key: connection_string_primary
                        name: azure-storage
