resources:
  - ../../../../bases/devops/kiroshi/essentials
  - ../../../../bases/devops/kiroshi/jobs/migrator
  - ../../../../bases/devops/kiroshi/checks/frontdoor/ips
  - ../../../../bases/devops/kiroshi/checks/frontdoor/ranges
  - ../../../../bases/devops/kiroshi/checks/frontdoor/traffic
  - ../../../../bases/devops/kiroshi/checks/spreedly/certs
  - ../../../../bases/devops/kiroshi/storage/blob/viator

namespace: devops

patches:
  - target:
      kind: CronJob
      name: kiroshi-traffic
    patch: |
      - op: replace
        path: /spec/suspend
        value: true
