---
bases:
  - ../../../../bases/olympus/asteria

configMapGenerator:
  - name: asteria
    namespace: default
    envs:
      - env.ini

replicas:
  - name: asteria
    count: 1

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: asteria
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: asteria
                env:
                  - name: POSTGRES_DSN
                    valueFrom:
                      secretKeyRef:
                        name: azure-pgfs
                        key: common_hermes
