---
bases:
  - ../../../../bases/olympus/styx

nameSuffix: -ts44
commonLabels:
  component: ts44

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: mode
            value: TS44
          - name: redis_url
            valueFrom:
              secretKeyRef:
                name: azure-redis-vnet
                key: uri_ssl
