bases:
- ../core

patches:
- path: patch-command.yaml
- path: patch-labels.yaml
- path: patch-limits.yaml
- path: patch-name.yaml
  target:
    kind: Deployment
- path: patch-replicas.yaml
  target:
    kind: Deployment
