---
bases:
  - ../base

nameSuffix: -migrator

commonLabels:
  component: migrator

replicas:
  - name: hermes-migrator
    count: 1

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/priorityClassName
        value: bink-high-tasks
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["bash", "-c", "sleep 10; python manage.py migrate; echo Done; tail -f /dev/null"]
      - op: replace
        path: /spec/template/metadata/annotations/prometheus.io~1scrape
        value: "false"
