---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loganalytics-to-tableau
  name: loganalytics-to-tableau
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loganalytics-to-tableau
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: app
      labels:
        app: loganalytics-to-tableau
        aadpodidbinding: tableau
    spec:
      containers:
        - image: binkcore.azurecr.io/loganalytics-to-tableau:latest
          name: app
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 10m
              memory: 384Mi
      imagePullSecrets:
        - name: binkcore.azurecr.io
