apiVersion: v1
kind: Service
metadata:
  labels:
    app: locust
    role: master
  name: locust-master
  namespace: default
spec:
  ports:
  - name: master-5557
    port: 5557
  - name: master-5558
    port: 5558
  - name: ui
    port: 8089
  selector:
    app: locust
    role: master
  type: ClusterIP
