---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: asteria
  name: asteria
  namespace: default
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: asteria
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        prometheus.io/port: '9100'
        prometheus.io/scrape: 'true'
        prometheus.io/job: asteria
        kubectl.kubernetes.io/default-container: app
      labels:
        app: asteria
    spec:
      priorityClassName: bink-low-component
      containers:
        - image: binkcore.azurecr.io/asteria:latest
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 9100
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 256Mi
      imagePullSecrets:
        - name: binkcore.azurecr.io
