[general]
"root_redirect_path" = "/v2"

[routes]
"v1.2" = "wallet/1.2.html"
"v1.3" = "wallet/1.3.html"
"v2" = "wallet/2.0.html"
"bpl" = "bpl/index.html"
"portal" = "portal/index.html"
"transaction" = "merchant/retail_transaction_api.html"
"midas_messaging" = "merchant/async/index.html"
"works" = "extras/givex.html"

"appendix" = "extras/appendix.html"
"changelog" = "extras/changelog.html"
