---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../../bases/devops/docs
  - ingress/root.yaml
configMapGenerator:
  - name: docs-config
    files:
      - config.toml
