apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../bases/devops/backups/cronjob
nameSuffix: -harmonia
commonLabels:
  database: harmonia
patches:
  - target:
      kind: CronJob
    patch: |
      - op: add
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/-
        value:
          name: PGDATABASE
          value: harmonia
