---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge
  namespace: default
  labels:
    app: bridge
spec:
  selector:
    matchLabels:
      app: bridge
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: app
        linkerd.io/inject: enabled
      labels:
        app: bridge
    spec:
      containers:
        - name: app
          image: binkcore.azurecr.io/bridge:latest
          env:
            - name: CONNECTION_STRING
              valueFrom:
               secretKeyRef:
                 name: azure-storage
                 key: connection_string_primary
          ports:
            - containerPort: 6502
              name: http
          resources:
            limits:
              memory: 256Mi
              cpu: 1000m
            requests:
              cpu: 10m
              memory: 256Mi
      priorityClassName: bink-high-tasks
      imagePullSecrets:
        - name: binkcore.azurecr.io
