apiVersion: batch/v1
kind: CronJob
metadata:
  name: snowstorm-freshservice
  namespace: default
  labels:
    app: snowstorm
    component: freshservice
spec:
  schedule: "0 23 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            linkerd.io/inject: enabled
            kubectl.kubernetes.io/default-container: app
          labels:
            app: snowstorm
            component: freshservice
        spec:
          containers:
            - name: app
              image: binkcore.azurecr.io/snowstorm:latest
              command: ["linkerd-await", "--shutdown", "--"]
              args: ["stormctl", "job", "freshservice", "--days=1"]
              resources:
                requests:
                  cpu: 100m
                  memory: 512Mi
                limits:
                  cpu: 1000m
                  memory: 512Mi
              securityContext:
                runAsGroup: 65534
                runAsUser: 65534
          restartPolicy: Never
          serviceAccountName: snowstorm
          imagePullSecrets:
            - name: binkcore.azurecr.io
      backoffLimit: 3
