---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyxis
  labels:
    app: pyxis
spec:
  selector:
    matchLabels:
      app: pyxis
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: app
      labels:
        app: pyxis
        aadpodidbinding: pyxis
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - pyxis
                topologyKey: topology.kubernetes.io/zone
              weight: 100
      containers:
        - name: app
          image: binkcore.azurecr.io/pyxis:latest
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 256Mi
      imagePullSecrets:
        - name: binkcore.azurecr.io
      serviceAccountName: pyxis
