---
resources:
  - ../base

nameSuffix: -consumer

commonLabels:
  component: consumer

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/priorityClassName
        value: bink-low-tasks
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["python", "-m", "hubble.cli", "activity-consumer"]
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: binkcore.azurecr.io/cosmos-admin:latest
