---
bases:
  - ../../../../bases/olympus/hermes/core
  - ../../../../bases/olympus/hermes/api
  - ../../../../bases/olympus/hermes/celery
  - ../../../../bases/olympus/hermes/migrator
  - ../../../../bases/olympus/hermes/logic

namespace: perf-api-v1

resources:
  - aad.yaml

configMapGenerator:
  - name: hermes
    envs:
      - env.ini

replicas:
  - name: hermes-api
    count: 6
  - name: hermes-celery
    count: 4

patches:
  - target:
      kind: Deployment
      name: hermes-api
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/livenessProbe
      - op: remove
        path: /spec/template/spec/containers/0/readinessProbe
  - target:
      kind: ServiceProfile
    patch: |-
      - op: replace
        path: /metadata/name
        value: hermes-api.perf-api-v1.svc.cluster.local
  - target:
      kind: Deployment
      name: hermes-api
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/securityContext
  - target:
      kind: Deployment
      name: hermes-api
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1250m
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hermes
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: hermes
                env:
                  - name: HERMES_BLOB_STORAGE_DSN
                    valueFrom:
                      secretKeyRef:
                        name: azure-storage-perf-api-v1
                        key: connection_string
                  - name: HERMES_DATABASE_URL_BARE
                    valueFrom:
                      secretKeyRef:
                        name: azure-pgfs
                        key: common_perf_api_v1_hermes
                  - name: HERMES_DATABASE_URL
                    value: $(HERMES_DATABASE_URL_BARE)&application_name=hermes
