---
bases:
  - ../base

nameSuffix: -task-worker

commonLabels:
  component: task-worker

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/priorityClassName
        value: bink-high-tasks
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["python", "-m", "polaris.core.cli", "task-worker"]
