---
resources:
  - ../../../bases/olympus/midas/api
  - ../../../bases/olympus/midas/beat
  - ../../../bases/olympus/midas/celery
  - ../../../bases/olympus/midas/consumer
  - aad.yaml

namespace: olympus

configMapGenerator:
  - name: midas
    envs:
      - env.ini

patches:
  - target:
      kind: ServiceProfile
    patch: |-
      - op: replace
        path: /metadata/name
        value: midas-api.barclays-sit.svc.cluster.local
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: midas
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: midas
                env:
                  - name: POSTGRES_DSN
                    valueFrom:
                      secretKeyRef:
                        name: azure-postgres
                        key: url_midas
