---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge
  namespace: default
  labels:
    app: bridge
spec:
  selector:
    matchLabels:
      app: bridge
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: app
        linkerd.io/inject: enabled
      labels:
        app: bridge
    spec:
      containers:
        - name: app
          image: binkcore.azurecr.io/bridge:latest
          env:
            - name: CONNECTION_STRING
              value: DefaultEndpointsProtocol=https;AccountName=binkuksouthprod;AccountKey=91n6awMXsn2TwMFuk18HZJFAbWalexuZR9CVwPO4xMPu0fBcnIkx4ejIUsiLF+8A/Y/Q3Km3ML+uJAsZlSU7Jw==;EndpointSuffix=core.windows.net
          ports:
            - containerPort: 6502
              name: http
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 256Mi
      imagePullSecrets:
        - name: binkcore.azurecr.io
