---
bases:
  - ../../../../bases/cosmos/event-horizon

namespace: bpl

resources:
  - aad.yaml

replicas:
  - name: event-horizon
    count: 3

configMapGenerator:
  - name: event-horizon
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: event-horizon
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: event-horizon
                env:
                  - name: POLARIS_DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-pgfs
                        key: common_polaris
                  - name: VELA_DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-pgfs
                        key: common_vela
                  - name: CARINA_DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-pgfs
                        key: common_carina
                  - name: DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-pgfs
                        key: common_placeholder
                  - name: REDIS_URL
                    valueFrom:
                      secretKeyRef:
                        key: uri_ssl
                        name: azure-redis-vnet
