---
bases:
  - ../../../../bases/cosmos/carina/core
  - ../../../../bases/cosmos/carina/api
  - ../../../../bases/cosmos/carina/migrator
  - ../../../../bases/cosmos/carina/task-worker
  - ../../../../bases/cosmos/carina/cron-scheduler

namespace: bpl

configMapGenerator:
  - name: carina
    envs:
      - env.ini

resources:
  - aad.yaml

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: carina
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: carina
                env:
                  - name: SQLALCHEMY_DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-postgres
                        key: url_carina
                  - name: BLOB_STORAGE_DSN
                    valueFrom:
                      secretKeyRef:
                        key: connection_string_primary
                        name: azure-storage
                  - name: KEY_VAULT_URI
                    valueFrom:
                      secretKeyRef:
                        key: url
                        name: azure-keyvault
