---
bases:
  - ../../../../bases/cosmos/carina/core
  - ../../../../bases/cosmos/carina/api
  - ../../../../bases/cosmos/carina/migrator
  - ../../../../bases/cosmos/carina/task-worker
  - ../../../../bases/cosmos/carina/cron-scheduler

namespace: bpl

configMapGenerator:
  - name: carina
    envs:
      - env.ini

resources:
  - aad.yaml

patches:
  - target:
      kind: Deployment
      name: carina-task-worker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["python", "-m", "carina.core.cli", "task-worker"]
  - target:
      kind: Deployment
      name: carina-cron-scheduler
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["python", "-m", "carina.core.cli", "cron-scheduler"]
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: carina
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: carina
                env:
                  - name: SQLALCHEMY_DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-pgfs
                        key: common_carina
                  - name: BLOB_STORAGE_DSN
                    valueFrom:
                      secretKeyRef:
                        key: connection_string
                        name: azure-storage-common
