---
resources:
  - ../base
  - service.yaml

nameSuffix: -api

commonLabels:
  component: api

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/metadata/annotations
        value: {"prometheus.io/port":"9100","prometheus.io/scrape":"true","prometheus.io/job":"carina"}
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe
        value: {"httpGet":{"path":"/readyz","port":9000,"scheme":"HTTP"},"initialDelaySeconds":15,"periodSeconds":60,"successThreshold":1,"timeoutSeconds":10}
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe
        value: {"httpGet":{"path":"/livez","port":9000,"scheme":"HTTP"},"initialDelaySeconds":15,"periodSeconds":60,"successThreshold":1,"timeoutSeconds":10}
      - op: add
        path: /spec/template/spec/priorityClassName
        value: bink-medium-api
