apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyvault-infra-sync
  namespace: kube-system
  labels:
    app: keyvault-infra-sync
    aadpodidbinding: keyvault-sync-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyvault-infra-sync
      aadpodidbinding: keyvault-sync-infra
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: app
      labels:
        app: keyvault-infra-sync
        aadpodidbinding: keyvault-infra-sync
    spec:
      serviceAccountName: keyvault-infra-sync
      containers:
      - name: app
        image: terrycain/keyvault2kube:1.1.0
        volumeMounts:
        - mountPath: /app/templates
          name: template-config
      volumes:
      - name: template-config
        configMap:
          defaultMode: 420
          name: keyvault-infra-sync
