apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bases/deployment

nameSuffix: -event-processor-harmonia

commonLabels:
  component: event-processor
  queue: tx-export-dw

patches:
  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args
        value: ["stormctl", "deploy", "events", "--queues=tx_export_dw"]
      - op: add
        path: /spec/template/spec/priorityClassName
        value: bink-high-tasks
