---
bases:
  - ../../../../bases/olympus/hades/api
  - ../../../../bases/olympus/hades/migrator

patches:
  - path: env.yaml
    target:
      kind: Deployment
  - target:
      kind: Deployment
      name: hades-api
    patch: |-
      - op: add
        path: /spec/replicas
        value: 3
