---
bases:
  - ../../../../bases/olympus/hades/api
  - ../../../../bases/olympus/hades/migrator

namespace: retail

configMapGenerator:
  - name: hades
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: hades
      spec:
        template:
          spec:
            containers:
            - name: app
              envFrom:
                - configMapRef:
                    name: hades
              env:
                - name: HADES_DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: azure-pgfs
                      key: common_retail_hades
