---
bases:
  - ../core

commonLabels:
  component: import-agent-iceland-bonus-card

nameSuffix: -import-agent-iceland-bonus-card

patches:
  - target:
      kind: Deployment
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: harmonia
        namespace: default
      spec:
        template:
          metadata:
            annotations:
              prometheus.io/port: '9100'
              prometheus.io/scrape: 'true'
              prometheus.io/job: harmonia-import-agent-iceland-bonus-card
          spec:
            containers:
              - name: app
                args: ["tximport", "--agent", "iceland-bonus-card", "--no-user-input", "--quiet"]
            priorityClassName: bink-low-tasks
