---
resources:
  - ../../../../bases/olympus/angelia
  - aad.yaml

namespace: olympus

configMapGenerator:
  - name: angelia
    envs:
      - env.ini

replicas:
  - name: angelia-api
    count: 6

patches:
  - target:
      kind: ServiceProfile
    patch: |-
      - op: replace
        path: /metadata/name
        value: angelia-api.olympus.svc.cluster.local
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: angelia
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: angelia
                env:
                  - name: POSTGRES_DSN
                    valueFrom:
                      secretKeyRef:
                        name: azure-postgres
                        key: url_hermes
                  - name: VAULT_URL
                    valueFrom:
                      secretKeyRef:
                        name: azure-keyvault
                        key: url
