resources:
  - ../../bases/deployments

commonLabels:
  type: distributor
  entity: visa-auth

nameSuffix: -distributor-visa-auth

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: [ cargo, run, --bin, distributor ]
