bases:
  - ../../../bases/infrastructure/prometheus-aks

namespace: prometheus

configMapGenerator:
  - name: alertmanager-rules
    files:
      - config/rules.yaml
  # - name: prometheus
  #   behavior: merge
  #   files:
  #     - config/config.yaml

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: prometheus
      spec:
        template:
          spec:
            containers:
              - name: prometheus
                volumeMounts:
                  - name: alertmanager-rules
                    mountPath: /etc/prometheus/rules.yaml
                    subPath: rules.yaml
            volumes:
              - configMap:
                  defaultMode: 420
                  name: alertmanager-rules
                name: alertmanager-rules
