---
bases:
  - ../base

resources:
  - service.yaml

nameSuffix: -controller

commonLabels:
  app: pyxis
  component: controller

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: pyxis
      spec:
        template:
          spec:
            containers:
              - name: app
                command:
                  - locust
                  - --master
                  - --host=http://localhost
                  - --master-port=5557
                  - --locustfile=locust_performance_testing/locustfile.py
                ports:
                  - containerPort: 8089
                    name: web
                  - containerPort: 5557
                    name: api-primary
                  - containerPort: 5558
                    name: api-secondary
              - name: nginx
                command:
                  - nginx
                image: binkcore.azurecr.io/pyxis:latest
                resources:
                  limits:
                    cpu: 1000m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 128Mi
