apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kirohsi
  namespace: default
spec:
  provider: azure
  parameters:
    clientID: ${kiroshi_client_id}
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: ${keyvault_name}
    tenantId: ${tenant_id}
    objects: |
      array:
        - |
          objectName: mastercard-sftp-keyfile
          objectType: secret
