---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobsf
  labels:
    app: mobsf
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mobsf
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: app
        linkerd.io/inject: enabled
      labels:
        app: mobsf
    spec:
      initContainers:
        - name: chown
          command: [chown, -R, 9901:9901, /mobsf]
          image: docker.io/alpine:3
          volumeMounts:
            - name: mobsf
              mountPath: /mobsf/
      containers:
        - name: app
          image: docker.io/opensecurity/mobile-security-framework-mobsf:v3.5.0
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: azure-pgfs
                  key: common_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azure-pgfs
                  key: common_password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: azure-pgfs
                  key: common_host
            - name: POSTGRES_DB
              value: mobsf
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 2Gi
          volumeMounts:
            - name: mobsf
              mountPath: /home/mobsf/.MobSF
      volumes:
        - name: mobsf
          persistentVolumeClaim:
            claimName: mobsf
