---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metis
  namespace: default
  labels:
    app: /metadata/annotations/buoyant.cloud
spec:
  selector:
    matchLabels:
      app: metis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: metis
        aadpodidbinding: metis
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - metis
                topologyKey: topology.kubernetes.io/zone
      containers:
        - image: binkcore.azurecr.io/metis:latest
          securityContext:
            runAsGroup: 65534
            runAsUser: 65534
          imagePullPolicy: Always
          name: app
          resources:
            limits:
              memory: 384Mi
            requests:
              memory: 384Mi
      imagePullSecrets:
        - name: binkcore.azurecr.io
