resources:
  - deployment.yaml

components:
  - ../../../common/pushgateway

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/metadata/labels
        value:
          aadpodidbinding: metis
