---
bases:
  - ../../../../bases/olympus/metis/api
  - ../../../../bases/olympus/metis/celery

resources:
  - aad.yaml

namespace: default

configMapGenerator:
  - name: metis
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
      name: metis-celery
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/command
        value:
          - celery
          - -A
          - metis.tasks
          - worker
          - --without-gossip
          - --without-mingle
          - --loglevel=info
          - --pool=solo
  - target:
      kind: Deployment
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: metis
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: metis
                env:
                  - name: PONTUS_DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-postgres
                        key: url_pontus
                  - name: AZURE_VAULT_URL
                    valueFrom:
                      secretKeyRef:
                        key: url
                        name: azure-keyvault
