apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightcity
  namespace: devops
  labels:
    app.kubernetes.io/name: nightcity
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: nightcity
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: nightcity
            azure.workload.identity/use: "true"
          annotations:
            kubectl.kubernetes.io/default-container: app
            linkerd.io/inject: enabled
        spec:
          serviceAccountName: nightcity
          containers:
            - name: app
              image: binkcore.azurecr.io/nightcity:latest
              imagePullPolicy: IfNotPresent
              command:
                - linkerd-await
                - --shutdown
                - --
              args:
                - tail
                - -f
                - /dev/null
              env:
                - name: KEYVAULT_URL
                  valueFrom:
                    secretKeyRef:
                      name: azure-keyvault
                      key: url
                - name: POSTGRES_HOST
                  valueFrom:
                    secretKeyRef:
                      name: azure-postgres
                      key: server_host
                - name: BLOB_STORAGE_ACCOUNT_NAME
                  valueFrom:
                    secretKeyRef:
                      name: azure-storage
                      key: blob_account_name
                - name: SFTP_STORAGE_ACCOUNT_NAME
                  valueFrom:
                    secretKeyRef:
                      name: azure-storage
                      key: sftp_account_name
              envFrom:
                - configMapRef:
                    name: nightcity
              resources:
                requests:
                  memory: 128Mi
                  cpu: 10m
                limits:
                  memory: 128Mi
              volumeMounts:
                - name: config
                  mountPath: /var/config
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: nightcity-config
