---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: 'true'
  name: airbyte.${cluster_name}.${cluster_location}.bink.sh
  namespace: datawarehouse
spec:
  rules:
    - host: airbyte.${cluster_name}.${cluster_location}.bink.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airbyte
                port:
                  number: 8000
  tls:
    - hosts:
        - airbyte.${cluster_name}.${cluster_location}.bink.sh
