apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pyqa-apiv2
    aadpodidbinding: pyqa-apiv2
  name: pyqa-apiv2
  namespace: default
spec:
  selector:
    matchLabels:
      app: pyqa-apiv2
      aadpodidbinding: pyqa-apiv2
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: app
      labels:
        app: pyqa-apiv2
        aadpodidbinding: pyqa-apiv2
    spec:
      containers:
      - name: app
        image: binkcore.azurecr.io/bink-api-v2-automation-suite:latest
        resources:
          limits:
            memory: 512Mi
      imagePullSecrets:
      - name: binkcore.azurecr.io
