---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: copybot
  name: copybot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copybot
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: app
        prometheus.io/port: '9091'
        prometheus.io/scrape: 'true'
        prometheus.io/job: copybot
      labels:
        app: copybot
    spec:
      priorityClassName: bink-high-tasks
      containers:
        - name: app
          image: binkcore.azurecr.io/copybot:latest
          args: [tail, -f, /dev/null]
          ports:
            - containerPort: 9091
              name: prometheus
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 128Mi
          securityContext:
            runAsGroup: 65534
            runAsUser: 65534
      terminationGracePeriodSeconds: 30
      serviceAccountName: copybot
      imagePullSecrets:
        - name: binkcore.azurecr.io
