---
resources:
  - namespace.yaml
  - service.yaml
  - serviceaccount.yaml
  - deploy.yaml

configMapGenerator:
  - name: rabbitmq
    namespace: default
    files:
      - config/enabled_plugins
      - config/rabbitmq.conf
