---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: proxy-postgres
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./overlays/uksouth-barclays/devops/proxy-postgres
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  images:
    - name: ghcr.io/binkhq/simpleproxy
      newName: ghcr.io/binkhq/simpleproxy
      newTag: 2022-02-01T052709Z    # {"$imagepolicy": "flux-system:uksouth-dev-simpleproxy:tag"}
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: simpleproxy
  namespace: flux-system
spec:
  image: ghcr.io/binkhq/simpleproxy
  interval: 120m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: uksouth-dev-simpleproxy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: simpleproxy
  filterTags:
    pattern: ^(?P<ts>\d{4}-\d{2}-\d{2}T\d{6}Z)$
    extract: $ts
  policy:
    alphabetical:
      order: asc
