resources:
- aad.yaml

bases:
- ../../../../bases/olympus/midas/api
- ../../../../bases/olympus/midas/beat
- ../../../../bases/olympus/midas/celery

patches:
- path: env.yaml
  target:
    kind: Deployment

namespace: sit
