apiVersion: v1
kind: ConfigMap
metadata:
  name: azure-metrics-exporter
  namespace: monitoring
data:
  azure.yml: |
    active_directory_authority_url: "https://login.microsoftonline.com/"
    resource_manager_url: "https://management.azure.com/"
    credentials:
      subscription_id: 79560fde-5831-481d-8c3c-e812ef5046e5
      client_id: 81fb8275-fbb2-472d-a0d4-23d03800e0d4
      client_secret:
      tenant_id: a6e2367a-92ea-4e5a-b565-723830bcc095
    targets:
    resource_groups:
      - resource_group: "uksouth-prod"
        resource_types:
          - "Microsoft.Cache/redis"
        metrics:
          - name: "connectedclients"
          - name: "errors"
          - name: "operationsPerSecond"
          - name: "percentProcessorTime"
          - name: "serverLoad"
          - name: "totalcommandsprocessed"
          - name: "usedmemory"
          - name: "usedmemorypercentage"
          - name: "usedmemoryRss"

      - resource_group: "uksouth-prod"
        resource_types:
          - "Microsoft.DBforPostgreSQL/servers"
        metrics:
          - name: "active_connections"
          - name: "connections_failed"
          - name: "cpu_percent"
          - name: "memory_percent"
          - name: "storage_percent"

      - resource_group: "uksouth-prod"
        resource_types:
          - "Microsoft.KeyVault/vaults"
        metrics:
          - name: "Availability"
          - name: "ServiceApiHit"
          - name: "ServiceApiLatency"
          - name: "ServiceApiResult"
          
      - resource_group: "uksouth-prod"
        resource_types:
          - "Microsoft.Storage/storageAccounts"
        metrics:
          - name: "Availability"
          - name: "Egress"
          - name: "Ingress"
          - name: "SuccessE2ELatency"
          - name: "SuccessServerLatency"
          - name: "Transactions"
          - name: "UsedCapacity"

      - resource_group: "uksouth-prod-k0"
        resource_types:
          - "Microsoft.Compute/virtualMachines"
        metrics:
          - name: "Disk Read Bytes"
          - name: "Disk Write Bytes"
          - name: "Network In Total"
          - name: "Network Out Total"
          - name: "Percentage CPU"

      - resource_group: "uksouth-prod-k0"
        resource_types:
          - "Microsoft.Network/loadBalancers"
        metrics:
          - name: "ByteCount"
          - name: "DipAvailability"
          - name: "PacketCount"
          - name: "SnatConnectionCount"
          - name: "SYNCount"
          - name: "VipAvailability"

      - resource_group: "uksouth-prod-k0"
        resource_types:
          - "Microsoft.Network/networkInterfaces"
        metrics:
          - name: "PacketsReceivedRate"
          - name: "PacketsSentRate"
