---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hermes
  namespace: default
  labels:
    app: hermes
spec:
  selector:
    matchLabels:
      app: hermes
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        aadpodidbinding: hermes
        app: hermes
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - hermes
                topologyKey: topology.kubernetes.io/zone
      containers:
        - image: binkcore.azurecr.io/hermes:latest
          command: [linkerd-await, --]
          securityContext:
            runAsGroup: 65534
            runAsUser: 65534
          imagePullPolicy: Always
          name: app
          resources:
            limits:
              memory: 384Mi
            requests:
              cpu: 10m
              memory: 384Mi
      imagePullSecrets:
        - name: binkcore.azurecr.io
      priorityClassName: hermes
      serviceAccountName: hermes
