---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: barclays-sit-ingress
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./overlays/uksouth-sandbox/barclays-sit/ingress
  prune: true
  dependsOn:
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
