---
bases:
  - ../base

nameSuffix: -migrator

commonLabels:
  component: migrator

patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["bash", "-c", "alembic upgrade head; echo Done; tail -f /dev/null"]
      - op: add
        path: /spec/template/spec/priorityClassName
        value: bink-high-tasks
