---
bases:
  - ../../../../bases/oss/api-reflector

namespace: retail

configMapGenerator:
  - name: api-reflector
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-reflector
      spec:
        template:
          spec:
            priorityClassName: bink-medium-api
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: api-reflector
                env:
                  - name: postgres_dsn
                    valueFrom:
                      secretKeyRef:
                        name: azure-pgfs
                        key: common_retail_api_reflector
