---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: 'true'
    nginx.ingress.kubernetes.io/enable-access-log: 'false'
  name: portal.${cluster_name}.${cluster_location}.bink.sh-healthz
  namespace: default
spec:
  rules:
    - host: portal.${cluster_name}.${cluster_location}.bink.sh
      http:
        paths:
          - path: /healthz
            pathType: Exact
            backend:
              service:
                name: healthz
                port:
                  number: 80
  tls:
    - hosts:
        - portal.${cluster_name}.${cluster_location}.bink.sh
