---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stats.${cluster_name}.${cluster_location}.bink.sh
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: 'true'
spec:
  rules:
    - host: stats.${cluster_name}.${cluster_location}.bink.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snowstorm-webserver
                port:
                  number: 80
  tls:
    - hosts:
        - stats.${cluster_name}.${cluster_location}.bink.sh
