---
bases:
  - ../base

nameSuffix: -task-worker

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: carina
        labels:
          component: task-worker
      spec:
        selector:
          matchLabels:
            component: task-worker
        template:
          metadata:
            labels:
              component: task-worker
          spec:
            containers:
              - name: app
                command: ["linkerd-await", "--"]
                args: ["python", "-m", "carina.core.cli", "task-worker"]
