---
bases:
  - ../../../../bases/olympus/iris

namespace: retail

configMapGenerator:
  - name: iris
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: iris
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: iris
                env:
                  - name: STORAGE_ACCOUNT_CONNECTION_STRING
                    valueFrom:
                      secretKeyRef:
                        key: connection_string
                        name: azure-storage-retail
