apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis-exporter
  name: redis-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        prometheus.io/port: '9100'
        prometheus.io/scrape: 'true'
        prometheus.io/job: redis
      labels:
        app: redis-exporter
    spec:
      containers:
      - name: redis-exporter
        image: binkext.azurecr.io/redis_exporter:v1.13.1
        imagePullPolicy: Always
        ports:
        - containerPort: 9100
        env:
        - name: REDIS_EXPORTER_PING_ON_CONNECT
          value: "true"
        - name: REDIS_EXPORTER_WEB_LISTEN_ADDRESS
          value: 0.0.0.0:9100
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
      imagePullSecrets:
      - name: binkext.azurecr.io
