---
bases:
  - ../../../../bases/olympus/europa/api
  - ../../../../bases/olympus/europa/migrator

resources:
  - aad.yaml

namespace: trusted-channels

configMapGenerator:
  - name: europa
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: europa
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: europa
