---
bases:
  - ../../../../bases/cosmos/event-horizon

namespace: bpl

resources:
  - aad.yaml

configMapGenerator:
  - name: event-horizon
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: event-horizon
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: event-horizon
                env:
                  - name: POLARIS_DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-postgres
                        key: url_polaris
                  - name: VELA_DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-postgres
                        key: url_vela
                  - name: CARINA_DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-postgres
                        key: url_carina
                  - name: DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-postgres
                        key: url_placeholder
                  - name: KEY_VAULT_URI
                    valueFrom:
                      secretKeyRef:
                        key: url
                        name: azure-keyvault
