---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: 'true'
  name: api2-docs.${cluster_name}.${location}.bink.sh
  namespace: default
spec:
  rules:
    - host: api2-docs.${cluster_name}.${location}.bink.sh
      http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: api2-redoc
                port:
                  number: 80
          - path: /bpl
            pathType: Prefix
            backend:
              service:
                name: api2-redoc
                port:
                  number: 80
          - path: /portal
            pathType: Prefix
            backend:
              service:
                name: api2-redoc
                port:
                  number: 80
          - path: /v1/*
            pathType: Prefix
            backend:
              service:
                name: api2-redoc
                port:
                  number: 80                  
          - path: /changelog.html
            pathType: Exact
            backend:
              service:
                name: api2-redoc
                port:
                  number: 80
          - path: /appendix.html
            pathType: Exact
            backend:
              service:
                name: api2-redoc
                port:
                  number: 80
  tls:
    - hosts:
        - api2-docs.${cluster_name}.${location}.bink.sh
