---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kibana.uksouth.bink.sh
  namespace: default
spec:
  dnsNames:
  - kibana.uksouth.bink.sh
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: letsencrypt
  secretName: kibana.uksouth.bink.sh
