---
bases:
  - ../../../../bases/olympus/iris

namespace: bpl

replicas:
  - name: iris-api
    count: 3

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: iris-api
      spec:
        template:
          spec:
            containers:
              - name: app
                env:
                  - name: STORAGE_CONTAINER
                    value: bpl-media
                  - name: STORAGE_CONTAINER_IN_URL
                    value: "false"
