---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carina
  namespace: default
  labels:
    app: carina
spec:
  selector:
    matchLabels:
      app: carina
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: app
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
        prometheus.io/job: carina
      labels:
        app: carina
        aadpodidbinding: carina
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - carina
                topologyKey: topology.kubernetes.io/zone
              weight: 100
      containers:
        - name: app
          image: binkcore.azurecr.io/carina:latest
          imagePullPolicy: Always
          securityContext:
            runAsGroup: 65534
            runAsUser: 65534
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 256Mi
      imagePullSecrets:
        - name: binkcore.azurecr.io
      serviceAccountName: carina
