---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-server-conf
  namespace: default
  labels:
    name: alertmanager-server-conf
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
      opsgenie_api_key: d91df60f-0052-4e54-b750-ff23bc731d46
      opsgenie_api_url: 'https://api.opsgenie.com/'

    mute_time_intervals:
      # Mute Intervals for office hours only
      - name: weekday_am_non_business_hours
        time_intervals:
          - weekdays: ['monday:friday']
            times:
            - start_time: '00:00'
              end_time: '07:00'
      - name: weekday_pm_non_business_hours
        time_intervals:
          - weekdays: ['monday:friday']
            times:
            - start_time: '19:00'
              end_time: '24:00'
      - name: weekend_non_business_hours
        time_intervals:
          - weekdays: ['saturday', 'sunday']

      # Mute Intervals for alerting at 10am on a Friday only
      - name: friday_alert_pre_mute
        time_intervals:
          - weekdays: ['friday']
            times:
            - start_time: '00:00'
              end_time: '10:00'
      - name: friday_alert_post_mute
        time_intervals:
          - weekdays: ['friday']
            times:
            - start_time: '11:00'
              end_time: '24:00'
      - name: friday_alert_day_mute
        time_intervals:
          - weekdays: ['sunday:thursday', 'saturday']

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 24h
      receiver: 'default'
      routes:
      - receiver: 'devops-test'
        matchers:
        - severity="testing"
      - receiver: 'alerts-devops'
        matchers:
        - alertname!~"^dev.*|staging.*|perf.*|monitoring.*|prod.*$"
        - severity=~"^S1.*|S2.*|P1.*|P2.*$"
        continue: true
      - receiver: 'alerts-devops_business_hours'
        matchers:
        - alertname!~"^dev.*|staging.*|perf.*|monitoring.*|prod.*$"
        - severity=~"^S3.*|P3.*$"
        continue: true
        mute_time_intervals:
          - weekday_am_non_business_hours
          - weekday_pm_non_business_hours
          - weekend_non_business_hours

      - receiver: 'alerts-development'
        matchers:
        - alertname=~"^dev.*$"
        - severity=~"^S1.*|S2.*|P1.*|P2.*$"
        continue: true
      - receiver: 'alerts-development_business_hours'
        matchers:
        - alertname=~"^dev.*$"
        - severity=~"^S3.*|P3.*$"
        continue: true
        mute_time_intervals:
          - weekday_am_non_business_hours
          - weekday_pm_non_business_hours
          - weekend_non_business_hours

      - receiver: 'alerts-staging'
        matchers:
        - alertname=~"^staging.*$"
        - severity=~"^S1.*|S2.*|P1.*|P2.*$"
        continue: true
      - receiver: 'alerts-staging_business_hours'
        matchers:
        - alertname=~"^staging.*$"
        - severity=~"^S3.*|P3.*$"
        continue: true
        mute_time_intervals:
          - weekday_am_non_business_hours
          - weekday_pm_non_business_hours
          - weekend_non_business_hours

      - receiver: 'alerts-performance'
        matchers:
        - alertname=~"^perf.*$"
        - severity=~"^S1.*|S2.*|P1.*|P2.*$"
        continue: true
      - receiver: 'alerts-performance_business_hours'
        matchers:
        - alertname=~"^perf.*$"
        - severity=~"^S3.*|P3.*$"
        continue: true
        mute_time_intervals:
          - weekday_am_non_business_hours
          - weekday_pm_non_business_hours
          - weekend_non_business_hours

      - receiver: 'alerts-production'
        matchers:
        - alertname=~"^prod.*$"
        - severity=~"^S1.*|S2.*|P1.*|P2.*$"
        continue: true
      - receiver: 'alerts-production_business_hours'
        matchers:
        - alertname=~"^prod.*$"
        - severity=~"^S3.*|P3.*$"
        continue: true
        mute_time_intervals:
          - weekday_am_non_business_hours
          - weekday_pm_non_business_hours
          - weekend_non_business_hours

      - receiver: 'monitoring'
        matchers:
        - alertname=~"^monitoring.*$"
        continue: true
      - receiver: 'opsgenie'
        matchers:
        - severity=~"^S1.*|P1.*$"
        continue: true

      - receiver: 'healthchecks'
        matchers:
        - severity="HEALTHCHECK"
        repeat_interval: 55m
        continue: true

      # Test Prometheus/Alertmanager/Teams/OpsGenie alert/callout chain
      - receiver: 'alerts-devops_friday_test'
        matchers:
        - severity="TEST"
        continue: true
        mute_time_intervals:
          - friday_alert_pre_mute
          - friday_alert_post_mute
          - friday_alert_day_mute
      - receiver: 'opsgenie_friday_test'
        matchers:
        - severity="TEST"
        continue: true
        mute_time_intervals:
          - friday_alert_pre_mute
          - friday_alert_post_mute
          - friday_alert_day_mute

    receivers:
    - name: 'default'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/aaeddfcd407742d398a9e8211e18ad36/de80162c-8e52-466b-affd-f3ccc0a66d5d'

    - name: 'devops-test'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/02d90eca65584c50ad988122ed58d4f1/bba71e03-172e-4d07-8ee4-aad029d9031d'

    - name: 'alerts-devops'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/aaeddfcd407742d398a9e8211e18ad36/de80162c-8e52-466b-affd-f3ccc0a66d5d'
    - name: 'alerts-devops_business_hours'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/aaeddfcd407742d398a9e8211e18ad36/de80162c-8e52-466b-affd-f3ccc0a66d5d'

    - name: 'alerts-development'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/8e773f1f096e468c8689e601f9d64fba/de80162c-8e52-466b-affd-f3ccc0a66d5d'
    - name: 'alerts-development_business_hours'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/8e773f1f096e468c8689e601f9d64fba/de80162c-8e52-466b-affd-f3ccc0a66d5d'

    - name: 'alerts-staging'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/fa0064dd228d4eca84b3264c13685380/de80162c-8e52-466b-affd-f3ccc0a66d5d'
    - name: 'alerts-staging_business_hours'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/fa0064dd228d4eca84b3264c13685380/de80162c-8e52-466b-affd-f3ccc0a66d5d'

    - name: 'alerts-performance'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/126cf7d774244b458c2b0e8a891fa0aa/de80162c-8e52-466b-affd-f3ccc0a66d5d'
    - name: 'alerts-performance_business_hours'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/126cf7d774244b458c2b0e8a891fa0aa/de80162c-8e52-466b-affd-f3ccc0a66d5d'

    - name: 'alerts-production'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/e6c8fe14130a4c69a213aebd2384ed14/de80162c-8e52-466b-affd-f3ccc0a66d5d'
    - name: 'alerts-production_business_hours'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/e6c8fe14130a4c69a213aebd2384ed14/de80162c-8e52-466b-affd-f3ccc0a66d5d'

    - name: 'monitoring'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/cc573c6a0b0648b5a53967684fe87fb8/de80162c-8e52-466b-affd-f3ccc0a66d5d'

    - name: 'healthchecks'
      webhook_configs:
      - url: 'https://hc-ping.com/98316b2f-4581-4620-add2-80c3adb52215'

    - name: 'opsgenie'
      opsgenie_configs:
      - send_resolved: false
        responders:
        - name: 'DevOps'
          type: 'team'

    # Test Prometheus/Alertmanager/Teams/OpsGenie alert/callout chain
    - name: 'alerts-devops_friday_test'
      webhook_configs:
      - url: 'http://localhost:2000/_dynamicwebhook/hellobink.webhook.office.com/webhookb2/bf220ac8-d509-474f-a568-148982784d19@a6e2367a-92ea-4e5a-b565-723830bcc095/IncomingWebhook/aaeddfcd407742d398a9e8211e18ad36/de80162c-8e52-466b-affd-f3ccc0a66d5d'
    - name: 'opsgenie_friday_test'
      opsgenie_configs:
      - send_resolved: false
        responders:
        - name: 'DevOps'
          type: 'team'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-msteams-tmpl
  namespace: default
  labels:
    name: prometheus-msteams-tmpl
data:
  msteams-message-card.tmpl: |-
    {{ define "teams.card" }}
    {
      "@type": "MessageCard",
      "@context": "http://schema.org/extensions",
      "themeColor": "{{- if eq .Status "firing" -}}FF0000
                     {{- else if eq .Status "resolved" -}}2DC72D
                     {{- else -}}808080
                     {{- end -}}",
      "summary": "Prometheus Alert",
      "title": "Prometheus Alert {{ .CommonLabels.severity }}",
      "sections": [ {{$externalUrl := .ExternalURL}}
      {{- range $index, $alert := .Alerts }}{{- if $index }},{{- end }}
        {
          "activityTitle": "{{- if eq .Status "firing" -}}<span style=color:red>FIRING</span> -&nbsp;
                            {{- else if eq .Status "resolved" -}}<span style=color:green>RESOLVED</span> -&nbsp;
                            {{- else -}}{{- end -}}
                            {{ $alert.Labels.alertname }}",
          "facts": [
            {{- range $key, $value := $alert.Annotations }}
            {
              "name": "{{ (title $key) }}",
              "value": "{{ $value }}"
            },
            {{- end -}}
            {{- if .StartsAt -}}
            {
              "name": "Started At",
              "value": "{{ .StartsAt }}"
            },
            {{- end -}}
            {{$endsAt := .EndsAt}}
            {{- if ne (.EndsAt | toString | substr 0 10) "0001-01-01" -}}
            {
              "name": "Ended At",
              "value": "{{ .EndsAt }}"
            },
            {{- end -}}
            {{$c := counter}}{{ range $key, $value := $alert.Labels }}{{if call $c}},{{ end }}
            {
              {{- if and (ne $key "alertname") (ne $key "severity") -}}
                "name": "{{ (title $key) }}",
                "value": "{{ $value }}"
              {{- end -}}
            }
            {{- end }}
          ],
          "markdown": true
        }
        {{- end }}
      ]
    }
    {{ end }}
