apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-crb-manager
  namespace: kube-system
  labels:
    app: kube-crb-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kube-crb-manager
  template:
    metadata:
      labels:
        app: kube-crb-manager
    spec:
      containers:
      - name: app
        image: binkcore.azurecr.io/kube-crb-manager:develop-2c16b6c5
      serviceAccountName: kube-crb-manager
      imagePullSecrets:
      - name: binkcore.azurecr.io
