apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../bases/deployment
labels:
  - includeSelectors: true
    pairs:
      component: import-agent-wasabi-club
nameSuffix: -import-agent-wasabi-club
patches:
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/template/metadata/annotations/prometheus.io~1job
        value: harmonia-import-agent-wasabi-club
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: ["tximport", "--agent", "wasabi-club", "--no-user-input", "--quiet"]
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
