---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: asset-register.tools.bink.sh
  namespace: default
spec:
  dnsNames:
  - asset-register.tools.bink.sh
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: letsencrypt
  secretName: asset-register.tools.bink.sh
