---
bases:
  - ../../../bases/olympus/hermes/api
  - ../../../bases/olympus/hermes/beat
  - ../../../bases/olympus/hermes/celery
  - ../../../bases/olympus/hermes/migrator
  - ../../../bases/olympus/hermes/logic

resources:
  - aad.yaml

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: HERMES_BLOB_STORAGE_DSN
            valueFrom:
              secretKeyRef:
                key: connection_string
                name: azure-storage-common
          - name: HERMES_BLOB_STORAGE_CONTAINER
            value: media/hermes
          - name: NO_AZURE_STORAGE
            value: 'False'
          - name: ENVIRONMENT_NAME
            value: Performance Sandbox Environment
          - name: ENVIRONMENT_COLOR
            value: '#FAC40F'
          - name: MIDAS_URL
            value: http://midas-api
          - name: LETHE_URL
            value: https://performance.sandbox.gb.bink.com/password
          - name: METIS_URL
            value: http://metis-api
          - name: HADES_URL
            value: http://hades-api
          - name: HERMES_SENTRY_DSN
            value: http://40ec46dd6a8940c4882501427e3e3a66@sentry-relay.monitoring/5589266
          - name: HERMES_SENTRY_ENV
            value: performance
          - name: SENTRY_SAMPLE_RATE
            value: '0.5'
          - name: CELERY_BROKER_URL
            value: amqps://perf-rabbitmq.uksouth.bink.host:5671
          - name: ATLAS_URL
            value: http://atlas-api
          - name: VAULT_URL
            value: https://bink-uksouth-perf-com.vault.azure.net/
          - name: VAULT_TOKEN
            value: abc123
          - name: SPREEDLY_BASE_URL
            value: http://pelops-api/spreedly
          - name: DEFAULT_API_VERSION
            value: '1.1'
          - name: HERMES_DEBUG
            value: 'True'
          - name: QUERY_LOG_LEVEL
            value: CRITICAL
          - name: SECURE_COOKIES
            value: "True"
          - name: THREAD_POOL_EXECUTOR_MAX_WORKERS
            value: "5"
          - name: JEFF_URL
            value: http://127.0.0.1:8080
          - name: OIDC_RP_REPLY_URL
            value: https://performance.sandbox.gb.bink.com/admin/oidc/callback/
          - name: OIDC_CLIENT_ID
            value: 1a5d83f3-da1f-401c-ac5f-d41c3fa0d9ef
          - name: OIDC_CLIENT_SECRET
            value: -NGSjpWWx_1w-6~.NkIl3lf~DC3Rg-.CMz
          - name: RABBIT_DSN
            value: amqps://perf-rabbitmq.uksouth.bink.host:5671
          - name: REDIS_URL
            valueFrom:
              secretKeyRef:
                key: uri_ssl
                name: azure-redis-vnet
          - name: HERMES_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: azure-pgfs
                key: common_hermes
  - target:
      kind: Deployment
      name: hermes-celery
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SENTRY_SAMPLE_RATE
          value: "0.01"
  - target:
      kind: Deployment
      name: hermes-beat
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: SENTRY_SAMPLE_RATE
          value: "0.01"
