---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: callbacca
  name: callbacca
  namespace: default
spec:
  selector:
    matchLabels:
      app: callbacca
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: app
        linkerd.io/inject: enabled
      labels:
        app: callbacca
    spec:
      containers:
        - image: binkcore.azurecr.io/callbacca:latest
          name: app
          ports:
            - containerPort: 9000
          resources:
            limits:
              cpu: 250m
              memory: 256M
            requests:
              memory: 256M
      priorityClassName: bink-low-tasks
      imagePullSecrets:
        - name: binkcore.azurecr.io
