---
resources:
  - ../base
  - ../service

nameSuffix: -admin

commonLabels:
  component: admin

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/priorityClassName
        value: bink-low-tasks
      - op: replace
        path: /spec/template/spec/containers/0/args
        value: [ 
          "gunicorn",
          "--workers=2",
          "--threads=2",
          "--error-logfile=-",
          "--access-logfile=-",
          "--bind=0.0.0.0:9000",
          "wsgi:app",
        ]
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: binkcore.azurecr.io/cosmos-admin:latest
