apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - deploy.yaml
configMapGenerator:
  - name: grafana
    files:
      - config/grafana.ini
