---
bases:
  - ../../default/midas

namespace: trusted-channels

replicas:
  - name: midas
    count: 0

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/env
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: midas
      spec:
        template:
          spec:
            containers:
              - name: app
                env:
                  - name: POSTGRES_DSN
                    value: postgresql://postgres@postgres:5432/midas
