apiVersion: v1
kind: Service
metadata:
  name: tableau-admin
  namespace: datawarehouse
spec:
  ports:
    - protocol: TCP
      port: 8850
      targetPort: 8850
---
apiVersion: v1
kind: Endpoints
metadata:
  name: tableau-admin
  namespace: datawarehouse
subsets:
  - addresses:
      - ip: 10.11.131.4
    ports:
      - port: 8850
---
apiVersion: v1
kind: Service
metadata:
  name: tableau
  namespace: datawarehouse
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: tableau
  namespace: datawarehouse
subsets:
  - addresses:
      - ip: 10.11.131.4
    ports:
      - port: 80
