---
resources:
  - ../../../../bases/olympus/angelia
  - aad.yaml

namespace: default

configMapGenerator:
  - name: angelia
    envs:
      - env.ini

replicas:
  - name: angelia-api
    count: 0

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: angelia
      spec:
        template:
          spec:
            containers:
              - name: app
                envFrom:
                  - configMapRef:
                      name: angelia
                env:
                  - name: POSTGRES_DSN
                    valueFrom:
                      secretKeyRef:
                        name: azure-postgres
                        key: url_hermes
