---
bases:
  - ../core

resources:
  - service.yaml

patches:
  - path: patch-annotations.yaml
  - path: patch-command.yaml
  - path: patch-labels.yaml
  - path: patch-name.yaml
    target:
      kind: Deployment

  - target:
      kind: Deployment
    patch: |
      - op: add
        path: /spec/template/spec/priorityClassName
        value: bink-medium-tasks
