---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harmonia
  namespace: default
  labels:
    app: harmonia
spec:
  selector:
    matchLabels:
      app: harmonia
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: harmonia
        aadpodidbinding: harmonia
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - harmonia
                topologyKey: topology.kubernetes.io/zone
      containers:
        - image: binkcore.azurecr.io/harmonia:latest
          securityContext:
            runAsGroup: 65534
            runAsUser: 65534
          imagePullPolicy: Always
          name: app
          resources:
            limits:
              memory: 128Mi
              cpu: 1000m
            requests:
              memory: 128Mi
              cpu: 10m
      imagePullSecrets:
        - name: binkcore.azurecr.io
