apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: kirohsi
  namespace: default
spec:
  provider: azure
  parameters:
    clientID: dummy
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: uksouth-prod-qj46
    tenantId: a6e2367a-92ea-4e5a-b565-723830bcc095
    objects: |
      array:
        - |
          objectName: amex-cert
          objectType: secret
        - |
          objectName: spreedly-oAuthUsername
          objectType: secret
        - |
          objectName: spreedly-oAuthPassword
          objectType: secret
