---
bases:
  - github.com/vectordotdev/vector/distribution/kubernetes/vector-agent?ref=v0.26.0

resources:
  - namespace.yaml

namespace: vector

configMapGenerator:
  - name: vector
    behavior: replace
    files:
      - config/agent.yaml

patches:
  - target:
      kind: DaemonSet
    patch: |-
      - op: add
        path: /metadata/annotations/buoyant.cloud~1excluded
        value: "true"
