---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: proxy-redis
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./overlays/uksouth-prod-legacy/devops/proxy-redis
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  images:
    - name: ghcr.io/binkhq/simpleproxy
      newName: ghcr.io/binkhq/simpleproxy
      newTag: latest
