---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: proxy-rabbitmq
  namespace: flux-system
spec:
  interval: 60m0s
  path: ./overlays/uksouth-prod-legacy/devops/proxy-rabbitmq
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
