---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: policies.${cluster_name}.${cluster_location}.bink.sh
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/service-upstream: 'true'
spec:
  rules:
    - host: policies.${cluster_name}.${cluster_location}.bink.sh
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: policies
                port:
                  number: 80
  tls:
    - hosts:
        - policies.${cluster_name}.${cluster_location}.bink.sh
