---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zephyrus-api
  namespace: default
  labels:
    app: zephyrus
    component: api
spec:
  selector:
    matchLabels:
      app: zephyrus
      component: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zephyrus
        component: api
        aadpodidbinding: zephyrus
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: app
        prometheus.io/port: '9100'
        prometheus.io/scrape: 'true'
        prometheus.io/job: zephyrus
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - zephyrus
                topologyKey: topology.kubernetes.io/zone
              weight: 100
      containers:
        - name: app
          image: binkcore.azurecr.io/zephyrus:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 192Mi
            requests:
              cpu: 10m
              memory: 192Mi
          securityContext:
            runAsGroup: 65534
            runAsUser: 65534
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /livez
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 10
      priorityClassName: bink-high-api
      imagePullSecrets:
        - name: binkcore.azurecr.io
