---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skiron-api
  namespace: default
  labels:
    app: skiron
    component: api
spec:
  selector:
    matchLabels:
      app: skiron
      component: api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: skiron
        component: api
      annotations:
        linkerd.io/inject: enabled
        kubectl.kubernetes.io/default-container: app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - skiron
                topologyKey: topology.kubernetes.io/zone
              weight: 100
      containers:
        - name: app
          image: binkcore.azurecr.io/skiron:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 120Mi
          securityContext:
            runAsGroup: 65534
            runAsUser: 65534
      priorityClassName: bink-high-api
      imagePullSecrets:
        - name: binkcore.azurecr.io
