---
# borrowed form https://github.com/fluxcd/flux2/tree/main/action#automate-flux-updates
name: update-flux

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  components:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main
      - name: Check for updates
        id: update
        run: |
          flux install \
            --components-extra=image-reflector-controller,image-automation-controller --export | tee \
              ./clusters/uksouth-barclays/flux-system/gotk-components.yaml \
              ./clusters/uksouth-dev/flux-system/gotk-components.yaml \
              ./clusters/uksouth-lloyds/flux-system/gotk-components.yaml \
              ./clusters/uksouth-perf/flux-system/gotk-components.yaml \
              ./clusters/uksouth-prod/flux-system/gotk-components.yaml \
              ./clusters/uksouth-retail/flux-system/gotk-components.yaml \
              ./clusters/uksouth-staging/flux-system/gotk-components.yaml
          VERSION="$(flux -v | cut -d " " -f 3)"
          echo "::set-output name=flux_version::$VERSION"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            branch: update-flux-${{ steps.update.outputs.flux_version }}
            assignees: |
              cpressland
              nathancread93
              thenu97
            commit-message: Update Flux to ${{ steps.update.outputs.flux_version }}
            title: Update Flux to ${{ steps.update.outputs.flux_version }}
