---
resources:
  - aad.yaml
  - ../../../../bases/olympus/metis/api
  - ../../../../bases/olympus/metis/celery

replicas:
  - name: metis
    count: 0

configMapGenerator:
  - name: metis
    envs:
      - env.ini

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: metis
      spec:
        template:
          spec:
            containers:
              - name: app
                env:
                  - name: PONTUS_DATABASE_URI
                    valueFrom:
                      secretKeyRef:
                        name: azure-postgres
                        key: url_pontus
                envFrom:
                  - configMapRef:
                      name: metis
